name: ci-cd-pipeline
on: push
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npm i
      - run: npm run build
      - run: npm run test
